server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://[::1]:10086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true
  sensitive-headers:   #让Cookies正常写入
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

leyou:
  jwt:
    secret: NimaAsILECNM&*^GA385[]{}UTRIOEUTG894&* # 登录校验的密钥
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: C:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000