server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.199.128
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5